### ISSUE TITLE
GNOME3 Shell theme

### ISSUE THREAD

**Issue by Feichtmeier** [shimmerproject/Greybird#177]
Would it be possible to add a GNOME3 Shell theme?
Thanks in advance

**Comment by ochosi** [comment]
It would and it has been requested in the past. However I'm not a Gnome user and I will consequently not be able to create or maintain such a theme.

**Comment by vanillajonathan** [comment]
Creating a theme is easiest if you inherit from the default gnome-shell theme and just override styles.
For inspiration on how to style the theme while adhering to the artist's vision you can look at the Plank theme.

The most important thing to style might be the top panel. Perhaps a good choice might be to use the RGBA color values 34, 34, 34, 204 that we find in the Plank theme.

File `Greybird/gnome-shell/gnome-shell.css`.
```css
@import url("/usr/share/gnome-shell/theme/gnome-shell.css");

/* Panel */

#panel {
    background-color: rgba(36, 36, 36, 204);
}
```
