### ISSUE TITLE
xfce-terminal has extra pixel border with >1 tab

### ISSUE THREAD

**Issue by ochosi** [shimmerproject/Greybird#184]
Full issue described here (incl screenshot).
https://bugs.launchpad.net/bugs/1683857

**Comment by casta** [comment]
confirmed with xfce4-terminal (last git revision), and having the same with mate-terminal (1.16) too.
Too bad, I cannot achieve to run gtk3 inspector on terminal apps to dig into the css selectors. It’s strangely not working (not able to select any window component on the terminal).

**Comment by f2404** [comment]
It appears there's an ancient bug against xfce4-terminal for that :) https://bugzilla.xfce.org/show_bug.cgi?id=3244
But, since this also happens with mate-terminal and gnome-terminal, I'm not sure whether it's a terminal issue.

**Comment by casta** [comment]
moreover it does not happen with other themes (like Zukitwo for example), and the old bug is related to gtk2, this one is for gtk3 too

**Comment by casta** [comment]
I have something that seems to work. Adding this to the .config/gtk-3.0/gtk.css fixes the issue:
```css
notebook > stack:not(:only-child) {
  border: 0;
}
notebook > header.top tabs {
  margin-bottom: 0;
}
notebook > header.bottom tabs {
  margin-top: 0;
}
notebook > header.left tabs {
  margin-right: 0;
}
notebook > header.right tabs {
  margin-left: 0;
}
```

It looks like the issue is Greybird setting a 1px border on `notebook > stack:not(:only-child)` where it should only do this on the notebook side having the tabs.
