### ISSUE TITLE
Drop down menus not rendering properly 

### ISSUE THREAD

**Issue by abhprk32** [shimmerproject/Greybird#265]
![Screenshot_2020-04-04_12-04-50](https://user-images.githubusercontent.com/24796764/78420411-864d9b80-766c-11ea-99ce-62367a8ce6f0.png)
OS- arch linux xfce 4.14

**Comment by nonamedotc** [comment]
I suspect this is not just drop-down menus. Please see this screenshot.

This is on Fedora 32, xfce 4.14.

gtk3-3.24.16
greybird-light-theme-3.22.12

![greybird](https://user-images.githubusercontent.com/1994161/79032697-7ce59700-7b76-11ea-939d-f1a127afd1ac.png)

**Comment by ochosi** [comment]
Ok wow, I need to check if I can reproduce that...

**Comment by Mau-G** [comment]
I'm unable to reproduce this in openSUSE Tumbleweed. 
gtk3-3.24.16

could this be a fedora packaging issue?

**Comment by nonamedotc** [comment]
> could this be a fedora packaging issue?

Could be except first comment shows similar issue in Arch - unless these are unrelated issues.

**Comment by abhprk32** [comment]
> I'm unable to reproduce this in openSUSE Tumbleweed.
> gtk3-3.24.16
> 
> could this be a fedora packaging issue?

I dont think so. I also tried changing fonts to check if my font settings were messing up some thing or not but it doesnt works.

**Comment by notarun** [comment]
Can reproduce this on Arch using gtk 3.24.17

![2020-04-12_04-39](https://user-images.githubusercontent.com/41166903/79056816-b63b0700-7c49-11ea-9f3f-2d237853ff14.png)

**Comment by notarun** [comment]
So, I came up with a hack to fix this issue. It only fixes styling for combo boxes and some buttons in header bar. Issue still persists in path bar.
```
.horizontal.linked > button:last-child {
  border-right-style: solid;
  border-right-width: 1px;
}
```
![2020-04-14_22-54](https://user-images.githubusercontent.com/41166903/79256477-9f79f780-7e77-11ea-84fc-ebf411e53cfd.png)

If someone can guide me throught the pathbar issue I will be able to make a pull request.

**Comment by birdie-github** [comment]
Fedora 32 - confirming.


![greybird2](https://user-images.githubusercontent.com/4958603/81130952-0780a280-8f39-11ea-9fbb-c94ff8e5a4ea.png)

**Comment by birdie-github** [comment]
Buttons are affected as well.

![logout](https://user-images.githubusercontent.com/4958603/82712339-4c197700-9c77-11ea-823f-028129488aa8.png)

**Comment by winterwolf** [comment]
Thanks @notarun, I added this rule to other elements:

```css
.horizontal.linked > entry:last-child {
  border-right-style: solid;
  border-right-width: 1px;
}

.horizontal.linked > button:last-child {
  border-right-style: solid;
  border-right-width: 1px;
}

.path-bar button.slider-button:last-child {
  border-right-style: solid;
  border-right-width: 1px;
}
```
